# Generated by Django 5.0.1 on 2024-02-05 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_cateogry', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('food_price', models.IntegerField()),
                ('food_desc', models.TextField()),
                ('food_image', models.ImageField(upload_to='items/')),
                ('food_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='canteen_admin.category')),
            ],
        ),
    ]
