# Generated by Django 5.0.1 on 2024-02-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_subcategory',
            field=models.CharField(max_length=50),
        ),
    ]
