# Generated by Django 5.0.1 on 2024-02-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='food_subcategory',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')], default='Breakfast', max_length=50),
            preserve_default=False,
        ),
    ]
